### ISSUE TITLE
Investigate how sandbox can work with multiple namespaces.

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-sandbox#103]
Currently, FF sandbox will only work with a single namespace. It seems like the biggest pain point is [firefly-sdk](https://github.com/hyperledger/firefly-sdk-nodejs) only allowing a single namespace per instance of the client.

**Comment by matthew1001** [comment]
(Draft PR being worked in https://github.com/hyperledger/firefly-sandbox/pull/108)

**Comment by Chengxuan** [comment]
Resolved by https://github.com/hyperledger/firefly-sandbox/pull/108
