### ISSUE TITLE
Sandbox UI's contracts tab shows only 3 APIs, with names truncated

### ISSUE THREAD

**Issue by nedgar** [hyperledger/firefly-sandbox#113]
In the FireFly Sandbox UI, the Contracts tab has a panel showing the available APIs, but it's basically unusable:
- it shows only 3 APIs max (not scrollable)
- the names are truncated (despite there being available horizontal space)
  - not helped by repeating prefix: `/sandbox/api/contracts/api` (though showing any sub-namespaces would make sense)
- there are various truncated white boxes that are confusing

![image](https://user-images.githubusercontent.com/692834/212964519-1af26b6d-0f8f-4e1a-85f6-2194a9d69043.png)

FYI @Chengxuan

**Comment by Chengxuan** [comment]
@nedgar the box shows all the APIs and is scrollable. But it's not an obvious UX as you need to scroll horizontally other than vertically.

**Comment by nedgar** [comment]
Nice, thanks for the usability improvements, @Chengxuan.
