### ISSUE TITLE
Token tab is disabled

### ISSUE THREAD

**Issue by satoshimum** [hyperledger/firefly-sandbox#124]
In case of running ff for hyperledger fabric I can't access the token tab from sandbox

<img width="571" alt="image" src="https://github.com/user-attachments/assets/1c981e77-5336-4946-bbfd-20f1e44ddcc7">

**Comment by EnriqueL8** [comment]
@satoshimum Did you have a token connector plugin enabled?

**Comment by satoshimum** [comment]
@EnriqueL8 I am new to firefly, I installed it and run it following the official documentation

```
ff init fabric
ff start dev
```

then opened the sandbox interface. How to enable such a plugin?

**Comment by EnriqueL8** [comment]
I see now - There are no token connectors for Fabric and that is why the sandbox is showing as disabled. 

Currently FireFly has token connector for Ethereum token standards such as ERC20, ERC721 and ERC1155

**Comment by satoshimum** [comment]
Thanks I was suspecting that.
HF supports these standards why no token connector is available?

**Comment by EnriqueL8** [comment]
Token connectors are a construct of FireFly to track token and just one for Fabric hasn't been contributed yet. By HF you mean Hyperledger Foundation and the token sdks for Fabric?

**Comment by satoshimum** [comment]
By HF I meant Hyperledger fabric. AFAIK most ETH standards can be implemented. If enough documentation is available, I am interested in building such a connector for firefly

**Comment by EnriqueL8** [comment]
@satoshimum Do you mind if we move this discussion to Discord?

**Comment by satoshimum** [comment]
No problem, I'll join the discord channel

**Comment by KrishnaPG** [comment]
Came across this while facing the same issue - what was the resolution?

**Comment by EnriqueL8** [comment]
You need to enable the token plugins to get that tab

**Comment by KrishnaPG** [comment]
Thank you @EnriqueL8 . But how to enable the token plugins? Any pointer to documentation or help would be greatly appreciated. The sandbox is created following the steps in the docs with `fabric` as below:
```
ff init fabric 
ff start dev
```

**Comment by EnriqueL8** [comment]
Ah we don't have token connectors for Fabric yet, only for Ethereum at the moment!
