### ISSUE TITLE
Run button in Register Contract API disabled for Fabric blockchains after creating FFI Interface

### ISSUE THREAD

**Issue by jsolderitsch** [hyperledger/firefly-sandbox#88]
![Screen Shot 2022-05-12 at 11 48 34 AM](https://user-images.githubusercontent.com/23091236/168297025-740b4f2a-7076-46a9-8be0-9edd888afa48.png)
I deployed the FFI for the asset-transfer-basic chaincode as described here:
[chaincode-example](https://github.com/hyperledger/firefly/blob/8d33b9fae5263c5993d1d6eae48742477852fc20/docs/tutorials/custom_contracts/fabric.md)
The screen shot shows the UI treatment when I tried to register a contract with this FFI
Is this a bug?

**Comment by nguyer** [comment]
@eberger727 Do you mind taking a look at this real quick? Seems like there might just be an issue with the logic in the frontend code that enables / disables the Run button here

**Comment by eberger727** [comment]
#89
