### ISSUE TITLE
Add 'firstEvent' field on Sandbox UI

### ISSUE THREAD

**Issue by nguyer** [hyperledger/firefly-sandbox#99]
Currently the Sandbox always subscribes from block `0`. When using a local chain that has very few blocks, this is fine. When using a public chain that already has millions of blocks, it would take a significant amount of time to index every block. Additionally, it is wasted computation to index blocks that happened before a contract of interest was deployed.

The Sandbox should have a field on the Contracts tab in the Listener section that allows the user to select the first event that the listener will index. This should be one of:
 - `"newest"`
 - `"oldest"`
 - a specific block number (an integer)
 The default value should be the same as the default in the FireFly API. I believe this is `"newest"` but we should double check this.

The Sandbox should have a field on the Tokens tab that allows the user to select the first event that the listener will index. This should be one of:
 - `"oldest"` (default)
 - a specific block number (an integer)

**Comment by shorsher** [comment]
For tokens, you just provide `blockNumber` in the `config` object, I don't believe `oldest` is a valid option.
